name: tickets
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.4.8
  firebase_core: ^2.23.0
  cloud_firestore: ^4.13.2
  riverpod_annotation: ^2.3.2
  http: 
  file_picker: ^6.1.1
  firebase_storage: ^11.5.2
  flutter_local_notifications: 
  geolocator: ^10.1.0
  geocoding: 

dev_dependencies:
  flutter_test:
    sdk: flutter

  riverpod_generator: ^2.3.8
  build_runner: 

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
